CREATE TABLE Student(ID BIGINT PRIMARY KEY, NAME VARCHAR, BIRTHDAY DATE, 'GROUP' INT);
CREATE TABLE Subject(ID BIGINT PRIMARY KEY, NAME VARCHAR, DESCRIPTION VARCHAR, GRADE INT);
CREATE TABLE PaymentType(ID BIGINT PRIMARY KEY, NAME VARCHAR);
CREATE TABLE Payment(ID BIGINT PRIMARY KEY, TYPE_ID BIGINT, FOREIGN KEY (TYPE_ID) REFERENCES PaymentType(ID),
                AMOUNT DECIMAL, STUDENT_ID BIGINT, FOREIGN KEY (STUDENT_ID) REFERENCES Student(ID), PAYMENT_DATE DATETIME);
CREATE TABLE Mark(ID BIGINT PRIMARY KEY, STUDENT_ID BIGINT, FOREIGN KEY (STUDENT_ID) REFERENCES Student(ID),
                  SUBJECT_ID BIGINT, FOREIGN KEY (STUDENT_ID) REFERENCES Subject(ID), MARK INT);


